project:
  type: website
  output-dir: docs

website:
  title: "BC1101"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: slides-index.qmd
        text: Slides

link-external-newwindow: true

format:
  html:
    toc: true

theme:
  light: custom.scss
  dark: custom-dark.scss

execute:
  freeze: auto
