project:
  type: website
  output-dir: docs

website:
  title: "BC1101"
  repo-url: https://github.com/robbrotherton/quarto-test-website
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: slides-index.qmd
        text: Slides
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub


link-external-newwindow: true

format:
  html:
    toc: true
    theme:
      light: custom.scss
      dark: custom.scss
  revealjs:
    chalkboard: true
    theme: custom-reveal.scss
    menu:
      transitions: true
    footer: '<button id="theme-toggle"><span id="moon" class="d-block d-block-light d-none">&#x263D;</span><span id="sun" class="d-block d-block-dark d-none">&#x263C;</span></button>'
    include-after-body: dark-reveal.js

execute:
  echo: false
  freeze: auto
