project:
  type: website

website:
  title: "BC1101"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: slides/slides-index.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
