project:
  type: website
  output-dir: docs

website:
  title: "BC1101"
  repo-url: https://github.com/robbrotherton/quarto-test-website
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: slides-index.qmd
        text: Slides
    right:
      - icon: github
        href: https://github.com/
        aria-label: GitHub


link-external-newwindow: true

format:
  html:
    toc: true

theme: custom.scss

execute:
  freeze: auto
