project:
  type: website
  output-dir: docs

website:
  title: "BC1101"
  navbar:
    left:
      - href: index.qmd
        text: Syllabus
      - href: slides/slides-index.qmd
        text: Slides

format:
  html:
    toc: true
    css: styles.css

execute:
  freeze: auto
