---
title: "PSYC BC1101 STATISTICS"
---

Professor: Dr. Rob Brotherton  
Email: rbrother@barnard.edu

Office Hours: TBD

Lecture hours: TBD 
Lecture venue: TBD


## Course Overview

This course, required for the psychology major, provides an introduction to statistical methods commonly used in psychological research. Topics include measures of central tendency and variability, probability and sampling, confidence intervals and hypothesis testing, t-test and analysis of variance, correlation and regression. In addition to learning the conceptual and mathematical underpinnings of these techniques, you will learn to calculate and interpret statistics with reference to real-world contexts and research questions typical in psychological research. The course includes recitation meetings that provide instruction in the analysis of psychological data using the R statistical software package commonly used by behavioral science researchers.

The course is designed to fulfill these goals:

-   Understand what statistics are, and why and when they are needed
-   Translate observations about the world into statistical statements and questions
-   Learn how statistical methods are used to test psychological hypotheses
-   Use statistical software (R) to describe, visualize, analyze, and report data




## Class Schedule

TBD

```{r eval=FALSE, echo=FALSE}

paste(seq.Date(from = as.Date("2022-01-01"), to = as.Date("2022-05-01"), by = "week"),
      seq.Date(from = as.Date("2022-01-03"), to = as.Date("2022-05-03"), by = "week"), sep = "!") |> 
  stringr::str_split(pattern = "!") |> 
  unlist()


tibble::tribble(
  ~Topic, ~Date,
  "One", "01/01/2022"
)
```



