---
format: html
title: "NHST"
---

:::: {#nhst-diagram style="font-size: 1.2em;"}

::: {#lines}
:::

::: {#treatment}
Treatment
:::

::: {#circle}
Original population    
$\mu, \sigma$
:::

::: {#circle style="right: 0; background-color: lightblue;"}
Treated population  
Unknown $\mu, \sigma$
:::

::: {#rect style="left: 0;"}
Sample
:::

::: {#rect style="right: 0; background-color: lightblue;"}
Treated sample  
$M, SD$
:::

::: {#population-comparison-line}
:::

::::


<style>

#nhst-diagram {
  position: relative; 
  width: 100%; 
  padding-bottom: 80%; 
  height: 0; 
  background-color: none;
}

#lines {
  width: 60%; 
  position: absolute; 
  top: 15%; 
  left: 20%; 
  height: 75%; 
  border-left: 2px dashed;
  border-bottom: 2px solid;
  border-right: 2px dashed;
}

#population-comparison-line {
  position: absolute; 
  width: 60%; 
  top: 5%; 
  left: 20%; 
  height: 75%; 
  border-radius: 50%;
  border-top: 2px dashed red;
  z-index: 10;
}

#treatment {
  position: absolute;
  background-color: lightblue;
  left: 45%;
  width: 10%;
  height: 100%;
  z-index: 9;
}

#circle {
  position: absolute;
  width: 40%; 
  height: 50%; 
  border-radius: 50%; 
  border: 1px solid;
  background-color: var(--background-color);
  z-index: 11;
}

#rect {
  position: absolute; 
  top: 80%; 
  right: 0; 
  width: 40%; 
  height: 20%; 
  background: lightblue; 
  border: 1px solid; 
  margin: 0;
  background-color: var(--background-color);
}


#rect > p, #circle > p {
  text-align: center;
  position: relative;
  top: 50%;
  -ms-transform: translateY(-50%);
  -webkit-transform: translateY(-50%);
  transform: translateY(-50%);
}

#treatment > p {
  writing-mode: vertical-lr;
  text-orientation: upright;
  text-align: center;
  position: relative;
  top: 50%;
  -ms-transform: translate(-30%, -50%);
  -webkit-transform: translate(-30%, -50%);
  transform: translate(-30%, -50%);
}



</style>
